version: 2.1
orbs:
  python: circleci/python@0.3.0
commands:
  # ここにコマンドを定義する
  setup_lib: # 基本ライブラリのセットアップ
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - run:
          name: install my libraly
          command: |
            pip install -e ./.
      - python/save-cache
jobs:
  # ジョブ（細かい処理）を定義する
  lint:
    executor: 
      name : python/default
      tag : "3.7.4"
    steps:
      - setup_lib
  test_add_subtract: # たし算、ひき算のテスト
    executor: python/default
    steps:
      - setup_lib
      - run:
          name: run test
          command: |
            pytest tests/test_calculator_addition.py tests/test_calculator_subtraction.py --junitxml=test-reports/junit.xml
      - store_test_results:
          path: test-reports
  test_multi_devison: # かけ算、わり算のテスト
    executor: 
      name : python/default
      tag : "3.7.4"
    steps:
      - setup_lib
      - run:
          name: run test
          command: |
            pytest tests/test_calculator_multiplication.py tests/test_calculator_division.py --junitxml=test-reports/junit.xml
      - store_test_results:
          path: test-reports
  test_covarege:
    executor: 
      name : python/default
      tag : "3.7.4"
    steps:
      - setup_lib
      - run:
          name: run test covarege
          command: |
            pytest --cov=src --cov-report=html --cov-fail-under=100
      - store_artifacts:
          path: htmlcov
  deploy:
    executor: 
      name : python/default
      tag : "3.7.4"
    steps:
      - setup_lib
  sphinx_making:
    executor:
      name : python/default
      tag : "3.7.4"
    steps:
      - setup_lib
  deploy_document_server:
    executor:
      name : python/default
      tag : "3.7.4"
    steps:
      - setup_lib
workflows:
  # ワークプロー（ジョブをまとめた一連の機能）
  public_reference: # ドキュメント生成、公開サイトへ配布
    jobs:
      - lint
      - sphinx_making:
          requires:
            - lint
      - deploy_document_server:
          requires:
            - sphinx_making
  test_calculator: # テスト、本番デプロイ
    jobs:
      - lint
      - test_add_subtract:
          requires:
            - lint
      - test_multi_devison:
          requires:
            - lint
      - test_covarege:
          requires:
            - test_add_subtract
            - test_multi_devison
      - deploy:
          requires:
            - test_covarege
