jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      #    name: install dependencies
      #    command: |
      #      python3 -m venv venv
      #      . venv/bin/activate
      #      pip install --upgrade pip
      #      pip install pytest
      #      pip install pytest-cov
      #      pip install -e ./.
  test1:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      #- run:
      #    name: install dependencies
      #    command: |
      #      python3 -m venv venv
      #      . venv/bin/activate
      #      pip install --upgrade pip
      #      pip install pytest
      #      pip install pytest-cov
      #      pip install -e ./.
      #- run:
      #    name: run test
      #    command: |
      #      . venv/bin/activate
      - run:
          name: install dependencies
          command: |
            pip install -e ./.
      - run:
          name: run test
          command: |
            #. venv/bin/activate
            pytest tests/test_calculator.py --junitxml=test-reports/junit.xml
  test2:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: install dependencies
          command: |
            pip install -e ./.
      - run:
          name: run test
          command: |
            pytest tests/test_calculator2.py --junitxml=test-reports/junit.xml
  cov:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - store-test-results:
          path: test-reports
      - run:
          name: run test-cov
          command: |
            pytest --cov=src
orbs:
  python: circleci/python@0.3.0
version: 2.1
workflows:
  Welcome:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - build
      - cov:
          requires:
            - test1
            - test2
