jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
  test1:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: install dependencies
          command: |
            pip install -e ./.
      - run:
          name: run test
          command: |
            #. venv/bin/activate
            pytest tests/test_calculator.py --junitxml=test-reports/junit.xml
  test2:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: install dependencies
          command: |
            pip install -e ./.
      - run:
          name: run test
          command: |
            pytest tests/test_calculator2.py --junitxml=test-reports/junit.xml
  test_coverage:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: install dependencies
          command: |
            pip install -e ./.
      - store_test_results:
          path: test-reports
      - run:
          name: run test-cov
          command: |
            pytest --cov=src
orbs:
  python: circleci/python@0.3.0
version: 2.1
workflows:
  Welcome:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - build
      - test_coverage:
          requires:
            - test1
            - test2
