version: 2.1
orbs:
  python: circleci/python@0.3.0
commands:
  # ここにコマンドを定義する
  setup_lib: # 基本ライブラリのセットアップ
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - run:
          name: install my libraly
          command: |
            pip install -e ./.
      - python/save-cache
jobs:
  lint:
    executor: 
      name : python/default
      tag : "3.7.4"
    steps:
      - setup_lib
  test_add_subtract:
    executor: python/default
    steps:
      - setup_lib
      - run:
          name: run test
          command: |
            pytest tests/test_calculator_addition.py tests/test_calculator_subtraction.py --junitxml=test-reports/junit.xml
      - store_test_results:
          path: test-reports
  test_multi_devison:
    executor: 
      name : python/default
      tag : "3.7.4"
    steps:
      - setup_lib
      - run:
          name: run test
          command: |
            pytest tests/test_calculator_multiplication.py tests/test_calculator_division.py --junitxml=test-reports/junit.xml
      - store_test_results:
          path: test-reports
  test_covarege:
    executor: 
      name : python/default
      tag : "3.7.4"
    steps:
      - setup_lib
      - run:
          name: run test covarege
          command: |
            pytest --cov=src --cov-report=html --cov-fail-under=100
      - store_artifacts:
          path: htmlcov
  deploy:
    executor: 
      name : python/default
      tag : "3.7.4"
    steps:
      - setup_lib
workflows:
  test_calculator:
    jobs:
      - lint
      - test_add_subtract:
          requires:
            - lint
      - test_multi_devison:
          requires:
            - lint
      - test_covarege:
          requires:
            - test_add_subtract
            - test_multi_devison
      - deplo:
          requires:
            - test_covarege
