version: 2.1
orbs:
  python: circleci/python@0.3.0
commands:
  # ここにコマンドを定義する
  setup_lib: # 基本ライブラリのセットアップ
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - run:
          name: install my libraly
          command: |
            pip install -e ./.
      - python/save-cache
jobs:
  lint:
    executor: python/default
    steps:
      - setup_lib
      - store_test_results:
          path: test-reports
  test_1:
    executor: python/default
    steps:
      - setup_lib
      - run:
          name: run test
          command: |
            pytest tests/test_calculator.py --junitxml=test-reports/junit.xml
      - store_test_results:
          path: test-reports
  test_2:
    executor: python/default
    steps:
      - setup_lib
      - run:
          name: run test
          command: |
            pytest tests/test_calculator2.py --junitxml=test-reports/junit.xml
      - store_test_results:
          path: test-reports
  test_covarege:
    executor: python/default
    steps:
      - setup_lib
      - run:
          name: run test covarege
          command: |
            pytest --cov=src --cov-report=html --cov-fail-under=100
      - store_test_results:
          path: test-reports
workflows:
  test_calculator1:
    jobs:
      - lint
      - test_1:
          requires:
            - lint
      - test_2:
          requires:
            - lint
      - test_covarege:
          requires:
            - test_1
            - test_2
  test_calculator2:
    jobs:
      - lint
      - test_1:
          requires:
            - lint
      - test_covarege:
          requires:
            - test_1
