version: 2.1
orbs:
  python: circleci/python@0.3.0
commands:
  # ここにコマンドを定義する
  setup_lib: # コマンド の名前（任意）
    steps: # 再利用したステップをここに記載
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: install dependencies
          command: |
            pip install -e ./.
jobs:
  lint:
    executor: python/default
    steps:
      - setup_lib
      - store_test_results:
          path: test-reports
  test_1:
    executor: python/default
    steps:
      - setup_lib
      - run:
          name: run test
          command: |
            pytest tests/test_calculator.py --junitxml=test-reports/junit.xml
      - store_test_results:
          path: test-reports
  test_2:
    executor: python/default
    steps:
      - setup_lib
      - run:
          name: run test
          command: |
            pytest tests/test_calculator2.py --junitxml=test-reports/junit.xml
      - store_test_results:
          path: test-reports
  test_covarege:
    executor: python/default
    steps:
      - setup_lib
      - run:
          name: run test-cov
          command: |
            pytest --cov=src
      - store_test_results:
          path: test-reports
workflows:
  test_calculator:
    jobs:
      - lint
      - test_1:
          requires:
            - lint
      - test_2:
          requires:
            - lint
      - test_covarege:
          requires:
            - test_1
            - test_2
