version: 2.1
orbs:
  python: circleci/python@0.3.0
commands:
  # ここにコマンドを定義する
  setup_lib: # コマンド の名前（任意）
    steps: # 再利用したステップをここに記載
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: install dependencies
          command: |
            pip install -e ./.
jobs:
  構文チェック:
    executor: python/default
    steps:
      - setup_lib
      - store_test_results:
          path: test-reports
  テスト（加算・減算）:
    executor: python/default
    steps:
      - setup_lib
      - run:
          name: run test
          command: |
            pytest tests/test_calculator.py --junitxml=test-reports/junit.xml
      - store_test_results:
          path: test-reports
  テスト（乗算・除算）:
    executor: python/default
    steps:
      - setup_lib
      - run:
          name: run test
          command: |
            pytest tests/test_calculator2.py --junitxml=test-reports/junit.xml
      - store_test_results:
          path: test-reports
  テストカバレッジ:
    executor: python/default
    steps:
      - setup_lib
      - run:
          name: run test-cov
          command: |
            pytest --cov=src
      - store_test_results:
          path: test-reports
workflows:
  計算機のテスト:
    jobs:
      - 構文チェック
      - テスト（加算・減算）:
          requires:
            - 構文チェック
      - テスト（乗算・除算）:
          requires:
            - 構文チェック
      - テストカバレッジ:
          requires:
            - テスト（加算・減算）
            - テスト（乗算・除算）
