version: 2
jobs:
  build1:
    docker:
      # - image: circleci/python:3.6.3
      - image: circleci/python:3.8.2
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install pytest
            pip install pytest-cov
            pip install -e ./.
      - run:
          name: run test
          command: |
            . venv/bin/activate
            pytest --junitxml=test-reports/junit.xml
      - store-test-results:
          path: test-reports
      - run:
          name: run test-cov
          command: |
            . venv/bin/activate
            pytest --cov=src
  build2:
    docker:
      # - image: circleci/python:3.6.3
      - image: circleci/python:3.8.2
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install pytest
            pip install pytest-cov
            pip install -e ./.
      - run:
          name: run test
          command: |
            . venv/bin/activate
            pytest --junitxml=test-reports/junit.xml
      - store-test-results:
          path: test-reports
      - run:
          name: run test-cov
          command: |
            . venv/bin/activate
            pytest --cov=srcworkflows:
  Welcome:
    jobs:
      - build1
      - build2
  version: 2
